---
title: "Getting_Started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting_Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


In this vignette, you'll download some sample data, run the FAMR package on it,
and examine the results. This should give you a good basic understanding of how
to run the software and examine its results. This vignette focuses on the main
`famr_susie` wrapper function, which runs several other internal functions.
For more advanced usage and documentation on specific functions, please see the
function documentation.


### Downloading sample data, understanding input format

To start, let's download some sample data:

```
wget https://zenodo.org/records/15191402/files/sample_data_famr.zip?download=1
unzip sample_data_famr.zip\?download\=1
rm sample_data_famr.zip\?download\=1 
```

Now go ahead and examine the directory structure. You'll notice that there are
two sub-directories, one with summary statistics files and one with linkage
disequilibrium (LD) matrices. Let's take a look at the summary statistics files:


``` #{r input_format_sumstats}
str(readRDS('sample_data_famr/summary_statistics/job_0_res__sumstats_locus_1.rds'))

# Should look like this:
# List of 8
#  $ betas    : num [1:100, 1:30] -0.00114 -0.01379 -0.01378 -0.0132 -0.00901 ...
#  $ stderrs  : num [1:100, 1:30] 0.0141 0.0141 0.0141 0.0141 0.0141 ...
#  $ Z        : num [1:100, 1:30] -0.0808 -0.9753 -0.9742 -0.9333 -0.6368 ...
#  $ zscores_y: num [1:100] 1.11 0.351 0.347 -0.807 0.462 ...
#  $ betas_y  : num [1:100] 0.01569 0.00496 0.00491 -0.01142 0.00653 ...
#  $ stderrs_y: num [1:100] 0.0141 0.0141 0.0141 0.0141 0.0141 ...
#  $ pos      : chr [1:100] "rs4303582" "rs77266488" "rs4583279" "rs201264110" ...
#  $ locus_idx: int [1:100] 1 1 1 1 1 1 1 1 1 1 ...
```

This shows you the format of the summary statistics input file. 
In this simulated dataset, there are 100 loci, with 100 SNPs each, and
30 exposures.
So there are 100 of these summary statistics files.
Each has the following fields:
* `betas`: A `(num_snp, num_exposure)` numeric matrix of marginal summary
statistics effect sizes (e.g. from GWAS) for each SNP in this locus on each 
exposure.
* `stderrs`: The corresponding standard errors for the `betas`
* `Z`: the corresponding Z-scores, i.e. `betas / stderrs`
* `pos`: the names of the SNPs

The above fields are required, but this file has additional fields. It has
`betas_y`, `stderrs_y`, and `zscores_y` which are vectors of summary statistics
for the outcome trait (`y`) for each SNP. These can be included in the summary
statistics files, as shown here, but can also be specified in a separate file;
see the `y_gwas_file` argument in for the `famr_susie` function in the 
documentation for `famr.R`. It also has a `locus_idx` which specifies which
locus these SNPs come from. This is normally stored internally and is not
needed as input.

Please note also that the names of the exposures should be included as the
column names of the `Z` matrix, as this is where the software pulls the exposure
names from. In our simulated data, the exposures are not named.

Similarly, we can look at the LD matrices:

``` #{r input_format_ld}
str(readRDS('sample_data_famr/ld_matrices/job_0_res__ld_locus_1.rds'))

 # num [1:100, 1:100] 1 -0.0684 -0.0684 -0.1645 0.2496 ...
 # - attr(*, "dimnames")=List of 2
 #  ..$ : chr [1:100] "rs4303582" "rs77266488" "rs4583279" "rs201264110" ...
 #  ..$ : chr [1:100] "rs4303582" "rs77266488" "rs4583279" "rs201264110" ...
```

These are just numeric `(num_snp, num_snp)` matrices giving the LD between each
pair of SNPs.

That's the file input format. `FAMR` is easiest to use if you have a directory
of summary statistics files and a separate directory of LD files, one each per
locus, which are alphabetically in the same order.

Let's now see how to run FAMR.


### Running the package, examining the results

Now let's load the FAMR package and run it on this sample data. 
Please note that the code may take a couple minutes to run. 
The code below assumes that your current working directory is the one you've 
downloaded the sample data into. 

We'll be running the main user-facing function, `famr_susie`.
Optionally, after loading the `FAMR` package, you can try running
`?famr_susie` to see a description of the function and available options.

``` #{r run_famr}
library(FAMR)

res = famr_susie('sample_data_famr/summary_statistics/',
                 'sample_data_famr/ld_matrices/')

```

To make the results easier to read, let's name the exposures.
Normally you won't have to do this if the exposure names are stored as the
column names of the `Z` matrix in the summary statistics files.
These simulated exposures don't have names, so we'll add them for readability.

``` #{r naming}
n_factor = length(res$pips$exposures) - 30
names(res$pips$exposures) = c(paste0('expo', 1:30), paste0('factor', 1:n_factor))
names(res$zscores$exposures) = names(res$pips$exposures)
```

Now let's examine the results. The main thing we want to look at is the
"posterior inclusion probabilities" (PIPs) of the variables, which indicate
the probability that each of the exposures and factors are causal.
We can also look at the marginal z-scores for each of these variables on the
outcome.

``` #{r pips_zscores}
res$pips$exposures
# Should look like:
#      expo1      expo2      expo3      expo4      expo5      expo6      expo7 
# 0.02168038 0.99999993 1.00000000 1.00000000 0.03006273 0.02086431 0.06564261 
#      expo8      expo9     expo10     expo11     expo12     expo13     expo14 
# 0.01245198 0.01370268 0.14287961 0.02131342 0.01176360 0.04154705 0.04598993 
#     expo15     expo16     expo17     expo18     expo19     expo20     expo21 
# 0.02630846 0.03138122 0.01241316 0.05116290 0.01697360 0.01172528 0.01712106 
#     expo22     expo23     expo24     expo25     expo26     expo27     expo28 
# 0.01412207 0.08089835 0.01236670 0.01174409 0.01187538 0.11216748 0.01420045 
#     expo29     expo30    factor1    factor2 
# 0.01952278 0.01228583 0.99999989 1.00000000 


res$zscores$exposures
# Should look like:
#          [,1]     [,2]    [,3]     [,4]     [,5]     [,6]     [,7]      [,8]
# [1,] 1.195137 7.718487 9.03478 11.53807 0.341561 1.408553 1.385941 -4.041805
#           [,9]      [,10]    [,11]     [,12]    [,13]    [,14]    [,15]
# [1,] 0.1843671 -0.8247518 1.246944 -3.631046 4.314023 -2.30429 4.793901
#         [,16]      [,17]     [,18]    [,19]     [,20]    [,21]     [,22]
# [1,] -1.63629 0.08748619 0.8926834 -3.18582 0.1878442 0.421557 0.7395468
#          [,23]     [,24]     [,25]      [,26]    [,27]     [,28]       [,29]
# [1,] -1.751231 -1.756996 -1.940141 -0.8266286 3.974921 0.9517898 0.007001429
#           [,30]    [,31]    [,32]
# [1,] -0.8680636 3.866268 5.542907
# attr(,"names")
#  [1] "expo1"   "expo2"   "expo3"   "expo4"   "expo5"   "expo6"   "expo7"  
#  [8] "expo8"   "expo9"   "expo10"  "expo11"  "expo12"  "expo13"  "expo14" 
# [15] "expo15"  "expo16"  "expo17"  "expo18"  "expo19"  "expo20"  "expo21" 
# [22] "expo22"  "expo23"  "expo24"  "expo25"  "expo26"  "expo27"  "expo28" 
# [29] "expo29"  "expo30"  "factor1" "factor2"
```

In this simulation, exposures 1-4 had a true causal effect on the outcome,
while exposures 5-30 were false positives. So we did well! We got three of the
four true exposures, and no false positives (assuming a PIP threshold of 0.9).
Exposure 1 has the weakest causal effect in the simulation, 
so it's not very surprising that we didn't capture that one.
Notice that the method infers two factors and also assigns them very high PIPs.
In the simulation, there are three true factors, each of which have a true
causal effect on the outcome. So we did well there too.

The z-score data is mostly what we'd expect -- the traits with high PIPs tend
to also have high z-scores.
However, there's a few interesting nuggets.
For example, exposure 8 has a fairly strong z-score of about -4.04, which is 
stronger that of inferred factor1, which has a z-score of about 3.9. 
Yet exposure 8 has a low PIP (as desired).

When factors are significantly correlated with the outcome, it is often 
interesting to see what exposures they are highly correlated with.
This can reveal some information about the biology the factor captures.
There's no real biology in this simulation, but as we'll see, it can also
reveal interesting things about what we see in our results.

We can look at the "R" matrix in the results object, which captures the 
correlations between traits inferred by FAMR:

``` #{r inferred_corrs}
library(Matrix)  # R is a sparse Matrix object

res$R[8,1:32]
# Should look like:
#  [1]  1.184749e-09 -2.785313e-02  3.160052e-03  1.701398e-02  1.019044e-02
#  [6] -1.286696e-02 -1.257566e-02  1.000000e+00 -5.366847e-02 -1.561301e-02
# [11] -4.302502e-02  1.342948e-02 -2.742825e-01 -9.099744e-04 -3.544528e-02
# [16]  2.026822e-01  8.945676e-02  1.107069e-01 -1.144439e-02 -3.069334e-02
# [21] -1.768171e-01 -5.851117e-02 -6.325104e-02 -1.649924e-02  1.483735e-01
# [26]  2.498381e-03  2.920885e-02 -1.332901e-02 -4.281362e-02  9.737442e-02
# [31]  6.100231e-03 -7.833054e-01
```

We're examining the correlation between exposure 8 and the other traits.
Factors are listed after exposures, so factor 2 is the 32nd trait (appearing
after the 30 exposures).
Here we see that exposure 8 has a strong negative correlation (`r=-0.78`)
with factor 2. Since factor 2 is strongly positively associated with the outcome
(`Z=5.5`), we can explain the negative association of exposure 8 (`Z=-4.0`)
due to its negative correlation with factor 2.
Thus, it is reasonable for FAMR to conclude that exposure 8 is not truly causal.

We note however that real data is often substantially more complicated and it is
not always so straightforward.


### Some other useful outputs

The FAMR results object has several other useful components. Some of these are:
* `susieres` stores the full SuSiE results object. SuSiE-RSS is what FAMR uses
for its regression step. Particularly useful to look at is `susieres$sets$cs$`,
which shows the "credible sets" inferred by SuSiE. One or more traits in each
credible set are inferred to have a causal effect, but SuSiE is unsure which
among the variables in a credible set are causal. See the SuSiE documentation
for more details. In our example, no credible sets have multiple traits.
* `priors` contains the priors inferred by the CTWAS-style framework of FAMR.
`priors$pi` are the prior probabilities of traits in each class (exposures and
SNPs being) causal, while `priors$sigma2` gives the prior variance of each 
class.
* `pips$factors` has the PIPs for factors fitted in a separate regression, with
only factors as predictor variables (no exposures or SNPs). FAMR places a heavy
prior on factors in the full regression, so sometimes this separate regression
provides a useful (yet rough) sensitivity analysis for the factors.